# -*- coding: utf-8 -*-
"""Fae_classification_dep.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lBweKWpe2opeDrhaksZoHa4NUYbOmOc9
"""



import streamlit as st
import pandas as pd
import joblib

model = joblib.load('fairy_type_prediction.pkl')
label_encoders = joblib.load('fairy_label_encoders.pkl')

st.title("🌸 FaeFinder 🌸")
st.write("Discover which type of fairy you are based on your personality and preferences ✨")

creativity = st.slider("🎨 Creativity", 1, 10, 5)
adventure = st.slider("🌿 Adventure", 1, 10, 5)
social_energy = st.slider("💃 Social Energy", 1, 10, 5)
nature_love = st.slider("🌱 Love for Nature", 1, 10, 5)
dreaminess = st.slider("🌙 Dreaminess", 1, 10, 5)
confidence = st.slider("✨ Confidence", 1, 10, 5)
emotionality = st.slider("💗 Emotionality", 1, 10, 5)
curiosity = st.slider("🔮 Curiosity", 1, 10, 5)

favorite_environment = st.selectbox(
    "🏡 What's your favorite environment?",
    label_encoders["Favorite_Environment"].classes_
)

favorite_season = st.selectbox(
    "🌸 What's your favorite season?",
    label_encoders["Favorite_Season"].classes_
)

favorite_time = st.selectbox(
    "🌙 What's your favorite time of day?",
    label_encoders["Favorite_Time"].classes_
)

favorite_color = st.selectbox(
    "🎀 What's your favorite color?",
    label_encoders["Favorite_Color"].classes_
)

favorite_environment_encoded = label_encoders["Favorite_Environment"].transform([favorite_environment])[0]

favorite_season_encoded = label_encoders["Favorite_Season"].transform([favorite_season])[0]

favorite_time_encoded = label_encoders["Favorite_Time"].transform([favorite_time])[0]

favorite_color_encoded = label_encoders["Favorite_Color"].transform([favorite_color])[0]

df = pd.DataFrame({
    "Creativity": [creativity],
    "Adventure": [adventure],
    "Social_Energy": [social_energy],
    "Nature_Love": [nature_love],
    "Dreaminess": [dreaminess],
    "Confidence": [confidence],
    "Emotionality": [emotionality],
    "Curiosity": [curiosity],
    "Favorite_Environment": [favorite_environment_encoded],
    "Favorite_Season": [favorite_season_encoded],
    "Favorite_Time": [favorite_time_encoded],
    "Favorite_Color": [favorite_color_encoded]
})

if st.button("✨ Discover My Fairy Type ✨"):
    prediction = model.predict(df)[0]
    fairy_type = label_encoders["Fairy_Type"].inverse_transform([prediction])[0]
    st.success(f"🧚‍♀️ You are a {fairy_type}!")